services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build:
      context: ./app/server
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern_notes
  frontend:
    build:
      context: ./app/frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  mongo_data:
